=== anne-parage/Interoperabilite/M2_Production/ordres_fabrication.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "IdOF": { "type": "string" },
      "IdCommande": { "type": "string" },
      "Date_Planification": { "type": "string", "format": "date" },
      "Date_lancement": { "type": "string", "format": "date" }
    },
    "required": ["IdOF", "IdCommande", "Date_Planification", "Date_lancement"]
  }
}

=== anne-parage/Interoperabilite/M2_Production/ordres_fabrication.json
[
  {"IdOF": "OF001", "IdCommande": "CMD501", "Date_Planification": "2026-02-05", "Date_lancement": "2026-02-10"},
  {"IdOF": "OF002", "IdCommande": "CMD502", "Date_Planification": "2026-02-07", "Date_lancement": "2026-02-12"},
  {"IdOF": "OF003", "IdCommande": "CMD503", "Date_Planification": "2026-02-10", "Date_lancement": "2026-02-15"},
  {"IdOF": "OF004", "IdCommande": "CMD504", "Date_Planification": "2026-02-12", "Date_lancement": "2026-02-17"}
]
