=== anne-parage/Interoperabilite/M2_Production/rapports_qualite.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "IdRapport": { "type": "string" },
      "IdUsine": { "type": "integer" },
      "Statut_conformite": { "type": "string" },
      "Date_controle": { "type": "string", "format": "date" }
    },
    "required": ["IdRapport", "IdUsine", "Statut_conformite", "Date_controle"]
  }
}

=== anne-parage/Interoperabilite/M2_Production/rapports_qualite.json
[
  {
    "IdRapport": "RQ001",
    "IdUsine": 9,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-05-14"
  },
  {
    "IdRapport": "RQ002",
    "IdUsine": 8,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-03-12"
  },
  {
    "IdRapport": "RQ003",
    "IdUsine": 5,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-20"
  },
  {
    "IdRapport": "RQ004",
    "IdUsine": 2,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-03-06"
  },
  {
    "IdRapport": "RQ005",
    "IdUsine": 10,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-07-03"
  },
  {
    "IdRapport": "RQ006",
    "IdUsine": 5,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-07-14"
  },
  {
    "IdRapport": "RQ007",
    "IdUsine": 8,
    "Statut_conformite": "Non Conforme",
    "Date_controle": "2026-05-14"
  },
  {
    "IdRapport": "RQ008",
    "IdUsine": 5,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-04"
  },
  {
    "IdRapport": "RQ009",
    "IdUsine": 6,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-02-10"
  },
  {
    "IdRapport": "RQ010",
    "IdUsine": 10,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-22"
  },
  {
    "IdRapport": "RQ011",
    "IdUsine": 5,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-03-13"
  },
  {
    "IdRapport": "RQ012",
    "IdUsine": 10,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-02-07"
  },
  {
    "IdRapport": "RQ013",
    "IdUsine": 5,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-03-25"
  },
  {
    "IdRapport": "RQ014",
    "IdUsine": 5,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-04-04"
  },
  {
    "IdRapport": "RQ015",
    "IdUsine": 1,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-07-14"
  },
  {
    "IdRapport": "RQ016",
    "IdUsine": 3,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-05-18"
  },
  {
    "IdRapport": "RQ017",
    "IdUsine": 4,
    "Statut_conformite": "Non Conforme",
    "Date_controle": "2026-06-27"
  },
  {
    "IdRapport": "RQ018",
    "IdUsine": 6,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-05-28"
  },
  {
    "IdRapport": "RQ019",
    "IdUsine": 1,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-02-15"
  },
  {
    "IdRapport": "RQ020",
    "IdUsine": 2,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-14"
  },
  {
    "IdRapport": "RQ021",
    "IdUsine": 10,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-07-21"
  },
  {
    "IdRapport": "RQ022",
    "IdUsine": 7,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-02-13"
  },
  {
    "IdRapport": "RQ023",
    "IdUsine": 1,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-03-26"
  },
  {
    "IdRapport": "RQ024",
    "IdUsine": 10,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-07-12"
  },
  {
    "IdRapport": "RQ025",
    "IdUsine": 2,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-02-08"
  },
  {
    "IdRapport": "RQ026",
    "IdUsine": 7,
    "Statut_conformite": "Non Conforme",
    "Date_controle": "2026-05-17"
  },
  {
    "IdRapport": "RQ027",
    "IdUsine": 2,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-04-24"
  },
  {
    "IdRapport": "RQ028",
    "IdUsine": 6,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-04-25"
  },
  {
    "IdRapport": "RQ029",
    "IdUsine": 3,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-21"
  },
  {
    "IdRapport": "RQ030",
    "IdUsine": 2,
    "Statut_conformite": "Non Conforme",
    "Date_controle": "2026-06-07"
  },
  {
    "IdRapport": "RQ031",
    "IdUsine": 6,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-07-27"
  },
  {
    "IdRapport": "RQ032",
    "IdUsine": 3,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-02-05"
  },
  {
    "IdRapport": "RQ033",
    "IdUsine": 5,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-03-20"
  },
  {
    "IdRapport": "RQ034",
    "IdUsine": 3,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-03-25"
  },
  {
    "IdRapport": "RQ035",
    "IdUsine": 8,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-25"
  },
  {
    "IdRapport": "RQ036",
    "IdUsine": 10,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-07-19"
  },
  {
    "IdRapport": "RQ037",
    "IdUsine": 10,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-07-11"
  },
  {
    "IdRapport": "RQ038",
    "IdUsine": 3,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-02-16"
  },
  {
    "IdRapport": "RQ039",
    "IdUsine": 8,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-04-19"
  },
  {
    "IdRapport": "RQ040",
    "IdUsine": 1,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-03"
  },
  {
    "IdRapport": "RQ041",
    "IdUsine": 5,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-05-02"
  },
  {
    "IdRapport": "RQ042",
    "IdUsine": 1,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-04-03"
  },
  {
    "IdRapport": "RQ043",
    "IdUsine": 2,
    "Statut_conformite": "Non Conforme",
    "Date_controle": "2026-06-17"
  },
  {
    "IdRapport": "RQ044",
    "IdUsine": 7,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-18"
  },
  {
    "IdRapport": "RQ045",
    "IdUsine": 1,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-21"
  },
  {
    "IdRapport": "RQ046",
    "IdUsine": 4,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-16"
  },
  {
    "IdRapport": "RQ047",
    "IdUsine": 9,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-02-15"
  },
  {
    "IdRapport": "RQ048",
    "IdUsine": 2,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-07-03"
  },
  {
    "IdRapport": "RQ049",
    "IdUsine": 9,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-02-08"
  },
  {
    "IdRapport": "RQ050",
    "IdUsine": 8,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-17"
  },
  {
    "IdRapport": "RQ051",
    "IdUsine": 10,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-04-12"
  },
  {
    "IdRapport": "RQ052",
    "IdUsine": 5,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-05-25"
  },
  {
    "IdRapport": "RQ053",
    "IdUsine": 6,
    "Statut_conformite": "Non Conforme",
    "Date_controle": "2026-02-26"
  },
  {
    "IdRapport": "RQ054",
    "IdUsine": 6,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-04-04"
  },
  {
    "IdRapport": "RQ055",
    "IdUsine": 9,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-04-09"
  },
  {
    "IdRapport": "RQ056",
    "IdUsine": 10,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-04-03"
  },
  {
    "IdRapport": "RQ057",
    "IdUsine": 10,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-04-10"
  },
  {
    "IdRapport": "RQ058",
    "IdUsine": 7,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-23"
  },
  {
    "IdRapport": "RQ059",
    "IdUsine": 2,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-13"
  },
  {
    "IdRapport": "RQ060",
    "IdUsine": 6,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-07-23"
  },
  {
    "IdRapport": "RQ061",
    "IdUsine": 9,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-07-22"
  },
  {
    "IdRapport": "RQ062",
    "IdUsine": 7,
    "Statut_conformite": "Non Conforme",
    "Date_controle": "2026-04-01"
  },
  {
    "IdRapport": "RQ063",
    "IdUsine": 6,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-03-07"
  },
  {
    "IdRapport": "RQ064",
    "IdUsine": 6,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-03-08"
  },
  {
    "IdRapport": "RQ065",
    "IdUsine": 3,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-02-10"
  },
  {
    "IdRapport": "RQ066",
    "IdUsine": 2,
    "Statut_conformite": "Non Conforme",
    "Date_controle": "2026-06-27"
  },
  {
    "IdRapport": "RQ067",
    "IdUsine": 9,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-07-11"
  },
  {
    "IdRapport": "RQ068",
    "IdUsine": 10,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-13"
  },
  {
    "IdRapport": "RQ069",
    "IdUsine": 3,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-03-27"
  },
  {
    "IdRapport": "RQ070",
    "IdUsine": 10,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-07-15"
  },
  {
    "IdRapport": "RQ071",
    "IdUsine": 1,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-04-22"
  },
  {
    "IdRapport": "RQ072",
    "IdUsine": 4,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-10"
  },
  {
    "IdRapport": "RQ073",
    "IdUsine": 8,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-08"
  },
  {
    "IdRapport": "RQ074",
    "IdUsine": 5,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-03-12"
  },
  {
    "IdRapport": "RQ075",
    "IdUsine": 10,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-05-25"
  },
  {
    "IdRapport": "RQ076",
    "IdUsine": 5,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-17"
  },
  {
    "IdRapport": "RQ077",
    "IdUsine": 7,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-03-26"
  },
  {
    "IdRapport": "RQ078",
    "IdUsine": 10,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-04-02"
  },
  {
    "IdRapport": "RQ079",
    "IdUsine": 8,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-06-04"
  },
  {
    "IdRapport": "RQ080",
    "IdUsine": 9,
    "Statut_conformite": "Conforme",
    "Date_controle": "2026-04-03"
  },
  {
    "IdRapport": "RQ081",
